[package]
name = "nannou-pendulum-basic-window"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_plot = "0.23.0"
nannou = "0.19.0"
nannou_egui = "0.19.0"
